project:
  type: website
  resources:
    - CV/
    - images/

website:
  title: "Gideon Ondap"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Curriculum Vitae.qmd
        text: Curriculum Vitae
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


